
version: '3'

services:

    app:
        restart: always
        build:
            context: .
        ports:
            - "8000:8000"
        command: npm start
        environment:
            NODE_ENV: development
        volumes:
            - ".:/src"
